name: Build and Deploy Spring Boot WAR to Azure

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission to Gradle
        run: chmod +x ./gradlew

      - name: Build WAR with Gradle
        run: /gradlew clean bootWar -x test

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: war-artifact
          path: build/libs/*.war

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: war-artifact

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy WAR to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: e-learning-platform
          slot-name: production
          package: '*.war'
